; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\xback\Documents\Visual Studio 2010\Projects\Buffers\Buffers\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUcyzxpUwlxfnvmghUerhfzoLhgfwrlLCABAUkilqvxghUyfuuvihUyfuuvihUivovzhvUhgwzucOlyq@
___@@_PchSym_@00@UfhvihUcyzxpUwlxfnvmghUerhfzoLhgfwrlLCABAUkilqvxghUyfuuvihUyfuuvihUivovzhvUhgwzucOlyq@ DD 01H DUP (?)
END
