; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.30319.01 

	TITLE	C:\Users\xback\Documents\Visual Studio 2010\Projects\Buffers\Buffers\dllmain.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_DllMain@12
EXTRN	?GetCPUInfo@@YAXXZ:PROC				; GetCPUInfo
; Function compile flags: /Odtp /ZI
; File c:\users\xback\documents\visual studio 2010\projects\buffers\buffers\dllmain.cpp
;	COMDAT _DllMain@12
_TEXT	SEGMENT
tv64 = -68						; size = 4
_hModule$ = 8						; size = 4
_ul_reason_for_call$ = 12				; size = 4
_lpReserved$ = 16					; size = 4
_DllMain@12 PROC					; COMDAT

; 10   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi

; 11   : 	switch (ul_reason_for_call)

	mov	eax, DWORD PTR _ul_reason_for_call$[ebp]
	mov	DWORD PTR tv64[ebp], eax
	cmp	DWORD PTR tv64[ebp], 1
	je	SHORT $LN2@DllMain
	jmp	SHORT $LN3@DllMain
$LN2@DllMain:

; 12   : 	{
; 13   : 	case DLL_PROCESS_ATTACH:
; 14   : 		GetCPUInfo();

	call	?GetCPUInfo@@YAXXZ			; GetCPUInfo
$LN3@DllMain:

; 15   : 		break;
; 16   : 	case DLL_THREAD_ATTACH:
; 17   : 	case DLL_THREAD_DETACH:
; 18   : 	case DLL_PROCESS_DETACH:
; 19   : 
; 20   : 		break;
; 21   : 	}
; 22   : 	return TRUE;

	mov	eax, 1

; 23   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
_DllMain@12 ENDP
_TEXT	ENDS
END
